### PR TITLE
Lesson _1_6

### PR DESCRIPTION
**Pull request by Manizha-khorram**

### CODE REVIEW

**Comment by geekiam23** [comment]
It looks like you are branching everything off of your main branch. It may be easier and get the full effect of git control if you branch each lesson off the next. For example, 1.6 off of 1.5. 1.5 off of 1.4. This will help bc you have a bug in 1.5 and when you fix it, it will auto update 1.6

**Comment by Manizha-khorram** [comment]
> It looks like you are branching everything off of your main branch. It may be easier and get the full effect of git control if you branch each lesson off the next. For example, 1.6 off of 1.5. 1.5 off of 1.4. This will help bc you have a bug in 1.5 and when you fix it, it will auto update 1.6


@geekiam23, I am sorry but I am not sure if I understand this correctly, so currently what I am doing is to create each branch after the current branch! And the reason was, my assignment has not been reviewed on time before, so for having all branches update I mad the next branch after the current one!
Should I change it and make each branch after the main branch?
Thanks

**Comment by geekiam23** [comment]
I created a [video](https://www.loom.com/share/3e7645650ee74ccf9569bea2302414a3) that I hope can explain what I'm trying to communicate. It is a tough concept to explain through text. You are not doing anything wrong. This is to help you clean up your git flow especially when you start working as a dev. Let me know if this helps or not.

**Comment by Manizha-khorram** [comment]
> I created a [video](https://www.loom.com/share/3e7645650ee74ccf9569bea2302414a3) that I hope can explain what I'm trying to communicate. It is a tough concept to explain through text. You are not doing anything wrong. This is to help you clean up your git flow especially when you start working as a dev. Let me know if this helps or not.

Many thanks for the clear explanation, it really helped.

**Review by geekiam23 — APPROVED** [review]
Great job

**Pull request merged**
