### PR TITLE
Lesson_1_5

### PR DESCRIPTION
**Pull request by Manizha-khorram**

### CODE REVIEW

**Review by geekiam23 — CHANGES_REQUESTED** [review]
Hey, I pulled down your work to test it out. Here is a [video](https://www.loom.com/share/b54a7bba076f483291efec590c8efb72).  There is a bug where you cannot a new todo item to your list. Please take a look and see if you can figure it out. If not you can reach out to one of the mentors and we would love to help you.

**Comment by Manizha-khorram** [comment]
Hi @geekiam23 , I wanted to play with it and make it more complicated for myself, so in case of choosing one of categories, it gonna be added otherwise I manage it not to be added!
So my question is, can I add some other functionalities when I am doing my assignment ?

**Comment by geekiam23** [comment]
Gotcha, that make sense. Feel free to add to it. One thing that could help is if you communicate what is added to the assignment. Also adding a video(I use loom) showing that you understand the original assignment. 

Good job on the assignment!

**Review by geekiam23 — APPROVED** [review]
Great job!!

**Comment by Manizha-khorram** [comment]
> Great job!!

Many thanks 🙏

**Pull request merged**
